### ISSUE TITLE
Discrepancies in scores between this gem and the zxcvbn JS

### ISSUE THREAD

**Issue by carlosa-suarez** [envato/zxcvbn-ruby#14]
Gentlemen,

This is just a simple replication to the question I raised in https://github.com/bitzesty/devise_zxcvbn/issues/11, since the gem used in this case belongs to ruby, (not devise as it was posted initially).

The problem is quite simple, the JS function returns zxcvbn('Obama!123').score = 3, while Ruby returns 1. I have the latest version of zxcvbn JS (4.2.0), Ruby (2.2.1), and zxcvbn-ruby (0.1.0)

is there any way I can solve this?

**Comment by bbn-github** [comment]
I believe you mean the other way around.

Did a test and I can see that zxcvbn.js returns a score of 1 vs. ruby scores it as 3.

Agree, would be interesting to understand the reason to the discrepancy.

**Comment by carlosa-suarez** [comment]
Hi, sorry this was replied on the link above, https://github.com/bitzesty/devise_zxcvbn/issues/11, this issue will be solved in the next release. They are not using ruby-zxcvbn anymore.
