### ISSUE TITLE
New warnings when running specs calling zxcvbn-ruby with latest Rake version

### ISSUE THREAD

**Issue by grempe** [envato/zxcvbn-ruby#19]
The following warnings are now thrown from including zxcvbn in the test suite of my ruby gem.  These just started showing up with the update of Rake from v10.5.0 to v11.1.2

```
$ bundle exec rake
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/zxcvbn-ruby-0.1.1/lib/zxcvbn/matchers/l33t.rb:34: warning: shadowing outer local variable - substitution
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/zxcvbn-ruby-0.1.1/lib/zxcvbn/entropy.rb:132: warning: `-' after local variable or literal is interpreted as binary operator
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/zxcvbn-ruby-0.1.1/lib/zxcvbn/entropy.rb:132: warning: even though it seems like unary operator
...
```

**Comment by joneslee85** [comment]
@grempe thanks for the report. Would you be able to submit a PR?

**Comment by grempe** [comment]
I am not able to take that on right now. Sorry.

**Comment by detj** [comment]
@joneslee85 I have submitted a PR regarding this https://github.com/envato/zxcvbn-ruby/pull/20

**Comment by detj** [comment]
@stevehodgkiss thanks for merging #20 

When can we expect this to land on RubyGems ?

**Comment by detj** [comment]
@johnsyweb Can we update RubyGems with the latest version? v0.1.2?

**Comment by johnsyweb** [comment]
Thanks for notifying me. I'll do thus today.

**Comment by johnsyweb** [comment]
https://rubygems.org/gems/zxcvbn-ruby/versions/0.1.2 has been published. Thanks for the fix, @detj.
